"use strict";

/*
 * Continuação incremental do DGP a partir do registro 61 da letra α.
 * Este arquivo é exclusivo da branch chat-gpt-dgp e permite acrescentar
 * novos lotes sem alterar o módulo principal dgp.js nem os módulos BDAG/LEH.
 */

window.ScripturaLexicons = window.ScripturaLexicons || {};

if (!window.ScripturaLexicons.DGP) {
    throw new Error("O módulo base do DGP deve ser carregado antes de dgp-batches.js.");
}


/* ==========================================================
   LOTE 4 — registros 61–80
   ========================================================== */

window.ScripturaLexicons.DGP.bibliographicTerms.push(
    { key: "bíbl.", type: "abbr", text: "bíblico; uso ou acepção atestada em textos bíblicos" },
    { key: "inf.", type: "abbr", text: "infinitivo" },
    { key: "Ésquilo", type: "biblio", text: "Ésquilo — poeta trágico ateniense dos séculos VI–V a.C., um dos três grandes tragediógrafos gregos clássicos." }
);

window.ScripturaLexicons.DGP.rowsHtml += String.raw`
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0061" data-source="DGP" data-search="ἁβρότης boa vida requinte opulência delicadeza indolência viço DGP" tabindex="0"><td class="table-lemma greek">ἁβρότης, ητος (ἡ)</td><td>—</td><td>boa vida; requinte; opulência</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0062" data-source="DGP" data-search="ἄβροτος imortal divino sem mortais homens DGP" tabindex="0"><td class="table-lemma greek">ἄβροτος, ος</td><td>—</td><td>imortal; divino</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0063" data-source="DGP" data-search="ἁβροχίτων túnica delicada cobertas finas DGP" tabindex="0"><td class="table-lemma greek">ἁβροχίτων, ωνος</td><td>—</td><td>com túnica delicada</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0064" data-source="DGP" data-search="ἄβροχος não molhado inundado chuva seco DGP" tabindex="0"><td class="table-lemma greek">ἄβροχος, ος, ον</td><td>—</td><td>não molhado; seco</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0065" data-source="DGP" data-search="ἁβρύνω tornar belo ornar mimar orgulhar DGP" tabindex="0"><td class="table-lemma greek">ἁβρύνω</td><td>—</td><td>tornar belo; mimar; orgulhar-se</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0066" data-source="DGP" data-search="ἁβρῶς delicadamente indolentemente langorosamente DGP" tabindex="0"><td class="table-lemma greek">ἁβρῶς</td><td>—</td><td>delicadamente; indolentemente</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0067" data-source="DGP" data-search="Ἀβυδηνός Abido território DGP" tabindex="0"><td class="table-lemma greek">Ἀβυδηνός, ή, όν</td><td>—</td><td>de Abido; território de Abido</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0068" data-source="DGP" data-search="Ἀβυδόθεν de Abido DGP" tabindex="0"><td class="table-lemma greek">Ἀβυδόθεν</td><td>—</td><td>de Abido</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0069" data-source="DGP" data-search="Ἀβυδόθι em Abido DGP" tabindex="0"><td class="table-lemma greek">Ἀβυδόθι</td><td>—</td><td>em Abido</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0070" data-source="DGP" data-search="Ἄβυδος Abido Trôade Egito cidade DGP" tabindex="0"><td class="table-lemma greek">Ἄβυδος, ου (ἡ)</td><td>—</td><td>Abido</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0071" data-source="DGP" data-search="ἄβυσσος fundo profundo insondável abismo mortos DGP" tabindex="0"><td class="table-lemma greek">ἄβυσσος, ος, ον</td><td>—</td><td>sem fundo; abismo</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0072" data-source="DGP" data-search="ἄγα dórico ἄγη DGP" tabindex="0"><td class="table-lemma greek">ἄγα</td><td>—</td><td>forma dórica de ἄγη</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0073" data-source="DGP" data-search="ἀγά dórico ἀγή DGP" tabindex="0"><td class="table-lemma greek">ἀγά</td><td>—</td><td>forma dórica de ἀγή</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0074" data-source="DGP" data-search="ἀγάασθαι ἀγάασθε infinitivo presente plural ἀγάομαι DGP" tabindex="0"><td class="table-lemma greek">ἀγάασθαι, ἀγάασθε</td><td>—</td><td>formas de ἀγάομαι</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0075" data-source="DGP" data-search="Ἀγαβάτανα Ἀγβάτανα DGP" tabindex="0"><td class="table-lemma greek">Ἀγαβάτανα</td><td>—</td><td>Ἀγβάτανα</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0076" data-source="DGP" data-search="ἀγαγεῖν infinitivo aoristo ἄγω DGP" tabindex="0"><td class="table-lemma greek">ἀγαγεῖν</td><td>—</td><td>infinitivo aoristo de ἄγω</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0077" data-source="DGP" data-search="ἄγαγον aoristo dórico ἄγω DGP" tabindex="0"><td class="table-lemma greek">ἄγαγον</td><td>—</td><td>aoristo dórico de ἄγω</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0078" data-source="DGP" data-search="ἀγάζω insistir importunar honrar venerar admirar irritar DGP Ésquilo" tabindex="0"><td class="table-lemma greek">ἀγάζω</td><td>—</td><td>insistir; venerar; admirar</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0079" data-source="DGP" data-search="ἀγάθεος dórico ἠγάθεος DGP" tabindex="0"><td class="table-lemma greek">ἀγάθεος</td><td>—</td><td>forma dórica de ἠγάθεος</td><td><span class="source-pill">DGP</span></td></tr>
<tr class="search-row" data-dictionary="grego" data-target="entry-dgp-0080" data-source="DGP" data-search="ἀγαθοεργέω ἀγαθουργέω fazer bem generoso bíblico DGP" tabindex="0"><td class="table-lemma greek">ἀγαθοεργέω-ῶ</td><td>—</td><td>fazer o bem; ser generoso</td><td><span class="source-pill">DGP</span></td></tr>
`;

window.ScripturaLexicons.DGP.cardsHtml += String.raw`
<article id="entry-dgp-0061" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἁβρότης, ητος (ἡ)</h1><div class="entry-meta"><span>DGP · ordem 61 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">1 boa vida; requinte; opulência 2 delicadeza; indolência 3 viço (da juventude). 〈ἁβρός〉</p></section></article>
<article id="entry-dgp-0062" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἄβροτος, ος</h1><div class="entry-meta"><span>DGP · ordem 62 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">e η, ον 1 imortal; divino 2 sem mortais; sem homens. 〈ἀ-, βροτός〉</p></section></article>
<article id="entry-dgp-0063" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἁβροχίτων, ωνος</h1><div class="entry-meta"><span>DGP · ordem 63 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">(masc., fem.) com túnica delicada; com cobertas finas. 〈ἁβρός, χιτών〉</p></section></article>
<article id="entry-dgp-0064" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἄβροχος, ος, ον</h1><div class="entry-meta"><span>DGP · ordem 64 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">1 não molhado; não inundado; que não se molha 2 a que falta chuva; sem água; seco. 〈ἀ-, βρέχω〉</p></section></article>
<article id="entry-dgp-0065" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἁβρύνω</h1><div class="entry-meta"><span>DGP · ordem 65 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">(aor. ἥβρυνα) 1 tornar belo; ornar delicadamente 2 mimar; tratar com delicadeza ♦ méd. 3 tomar ares afetados, superiores; tornar-se orgulhoso 4 orgulhar-se de, dat. 〈ἁβρός〉</p></section></article>
<article id="entry-dgp-0066" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἁβρῶς</h1><div class="entry-meta"><span>DGP · ordem 66 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">adv. delicadamente; indolentemente; langorosamente.</p></section></article>
<article id="entry-dgp-0067" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">Ἀβυδηνός, ή, όν</h1><div class="entry-meta"><span>DGP · ordem 67 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">1 de Abido ♦ ἡ Ἀβυδηνή [χώρη] 2 o território de Abido. 〈Ἄβυδος〉</p></section></article>
<article id="entry-dgp-0068" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">Ἀβυδόθεν</h1><div class="entry-meta"><span>DGP · ordem 68 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">adv. de Abido. 〈Ἄβυδος〉</p></section></article>
<article id="entry-dgp-0069" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">Ἀβυδόθι</h1><div class="entry-meta"><span>DGP · ordem 69 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">adv. em Abido. 〈Ἄβυδος〉</p></section></article>
<article id="entry-dgp-0070" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">Ἄβυδος, ου (ἡ)</h1><div class="entry-meta"><span>DGP · ordem 70 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">Abido, cidade grega da Trôade; cidade do Egito.</p></section></article>
<article id="entry-dgp-0071" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἄβυσσος, ος, ον</h1><div class="entry-meta"><span>DGP · ordem 71 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">1 sem fundo; profundo 2 insondável ♦ ἡ ἄβυσσος 3 abismo 4 bíbl. o abismo, habitação dos mortos. 〈ἀ-, βυσσός〉</p></section></article>
<article id="entry-dgp-0072" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἄγα</h1><div class="entry-meta"><span>DGP · ordem 72 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">dór. = ἄγη.</p></section></article>
<article id="entry-dgp-0073" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἀγά</h1><div class="entry-meta"><span>DGP · ordem 73 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">dór. = ἀγή.</p></section></article>
<article id="entry-dgp-0074" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἀγάασθαι, ἀγάασθε</h1><div class="entry-meta"><span>DGP · ordem 74 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">inf. pres. e 2ª pl. pres. de ἀγάομαι.</p></section></article>
<article id="entry-dgp-0075" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">Ἀγαβάτανα</h1><div class="entry-meta"><span>DGP · ordem 75 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">Ἀγβάτανα.</p></section></article>
<article id="entry-dgp-0076" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἀγαγεῖν</h1><div class="entry-meta"><span>DGP · ordem 76 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">inf. aor.2 de ἄγω.</p></section></article>
<article id="entry-dgp-0077" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἄγαγον</h1><div class="entry-meta"><span>DGP · ordem 77 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">aor.2 dór. de ἄγω.</p></section></article>
<article id="entry-dgp-0078" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἀγάζω</h1><div class="entry-meta"><span>DGP · ordem 78 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">(só pres.) 1 insistir demais; importunar: τὰ θεῶν μηδὲν ἀγάζειν Ésquilo não exigir demasiado dos deuses ♦ méd. 2 honrar; venerar; admirar 3 tard. irritar-se; indignar-se.</p></section></article>
<article id="entry-dgp-0079" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἀγάθεος</h1><div class="entry-meta"><span>DGP · ordem 79 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">dór. = ἠγάθεος.</p></section></article>
<article id="entry-dgp-0080" class="entry-card" data-dictionary="grego" data-source="DGP" hidden><header class="entry-header"><div><h1 class="entry-title greek">ἀγαθοεργέω-ῶ</h1><div class="entry-meta"><span>DGP · ordem 80 na letra α</span></div></div><div class="source-tag">DGP</div></header><div class="entry-divider"></div><section class="entry-section"><div class="section-title">Definição do DGP</div><p class="entry-text">e ἀγαθουργέω-ῶ bíbl. fazer o bem; ser generoso. 〈ἀγαθοεργός〉</p></section></article>
`;

document.write('<script src="lexicons/dgp-batch-005.js"><\/script>');
document.write('<script src="lexicons/dgp-batch-006.js"><\/script>');
